### ISSUE TITLE
informações sobre métodos

### ISSUE THREAD

**Issue by youngkaneda** [gpes/parse-review#1]
consegui extrair todas as informações que me foram exigidas, utilizei  o método "getDeclaringClass()" pra ter acesso as informações sobre a expressão que invoca o método, junto com o seu tipo. O que falta agora é criar uma classe, que armazene todas essas informações, e adicioná-la em uma lista.

**Comment by ricardojob** [comment]
Quais informações já são extraída corretamente?

**Comment by ricardojob** [comment]
@juanpablolvl99, o que ocorre se substituirmos na classe `SessionFactory` o método `closeDriver` para `
public static void closeDriver() {
        driver.close();
        SessionFactory.a().add(null);
    }`

Qual seria a saída?

**Comment by juanpablolvl99** [comment]
@ricardojob creio eu que todas as informações necessárias que são
Nome da classe
   - métodos declarados 
       - nome
       - tipo de retorno totalmente qualificado
   - métodos invocados 
       - nome
       - tipo de retorno totalmente qualificado
       - classe da expressão totalmente qualificado que invoca o método 
       - identificador da expressão que invoca o método (caso não haja retorna nulo)

**Comment by youngkaneda** [comment]
@ricardojob creio eu que todas as informações necessárias que são

Nome da classe

   - métodos declarados
       - nome
       - tipo de retorno totalmente qualificado
   - métodos invocados
       - nome
       - tipo de retorno totalmente qualificado
       - classe da expressão totalmente qualificado que invoca o método
       - identificador da expressão que invoca o método (caso não haja retorna nulo)

**Comment by youngkaneda** [comment]
@ricardojob a saída para a pergunta que você tinha feito : 
-who invoked add? SessionFactory.a()
	-who invoked type java.util.List<java.lang.String>	name add	return type boolean
	-who invoked a? SessionFactory
	-who invoked type com.mycompany.atividade.fabrica.SessionFactory	name a	return type java.util.List<java.lang.String>
